export const ADD_CUSTOMER = 'ADD_CUSTOMER'
export const ADD_ACCOUNT = 'ADD_ACCOUNT'
export const SEARCH_TERM = 'SEARCH_TERM'

export const WITHDRAW_ACCOUNT = 'WITHDRAW_ACCOUNT'
export const NEW_AMOUNT_TO = 'NEW_AMOUNT_TO'
export const NEW_AMOUNT_FROM = 'NEW_AMOUNT_FROM'


// Teller Types
export const SET_USER_ID = 'SET_USER_ID'
export const SET_USER_PASSWORD = 'SET_USER_PASSWORD'
export const SET_NEW_USER_ID = 'SET_NEW_USER_ID'
export const SET_NEW_USER_PASSWORD = 'SET_NEW_USER_PASSWORD'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'